#spring.profiles.active=production

spring.datasource.url=jdbc:postgresql://localhost:5432/todo?
spring.datasource.username=postgres
spring.datasource.password=postgres
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=tru

server.port=8090

# JWT Configuration
jwt.secret=${JWT_SECRET:bXlTZWNyZXRLZXlGb3JKd3RUb2tlbkdlbmVyYXRpb25NdXN0QmVMb25nRW5vdWdoMjU2Qml0cw==}
jwt.access-token-expiration=3600000
#jwt.access-token-expiration=10000
jwt.refresh-token-expiration=604800000

# App version
app.version=${APP_VERSION:0.0.1}
app.min-android-version=${MIN_ANDROID_VERSION:1}