# Disable Swagger UI and API docs on production
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false
springdoc.swagger-ui.path=/disabled
springdoc.api-docs.path=/disabled

# CORS - only HTTPS domain on production
app.cors-origins=https://todo.keepware.ru,https://todo.mngerasimenko.ru
